# This workflow will review a GloBI indexed dataset.
# For more information see: https://globalbioticinteractions.org

name: Name Alignment by Nomer

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  align:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8   
    - name: download alignment script
      run: curl --silent -L "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/align-names.sh" > align-names.sh
    - name: align names
      run: bash align-names.sh "${GITHUB_REPOSITORY}" 
